/*File name: generator.c---------------------------------------------*
 |Project:    Implementace překladače imperativního jazyka IFJ20     |
 |Team:       124, varianta II                                       |
 |Authors:    Viktor Rucký (xrucky01)                                |
 |                                                                   |
 |  _      _     _   __                   __  _        _             |
 | | |    (_)   | | /_/                  /_/ | |      | |            |
 | | |     _  __| | ___   _   _  __   ___   _| |_ __ _| |__  _   _   |
 | | |    | |/ _` |/ _ \ | | | | \ \ / / | | | __/ _` | '_ \| | | |  |
 | | |____| | (_| |  __/ | |_| |  \ V /| |_| | || (_| | | | | |_| |  |
 | |______|_|\__,_|\___|  \__,_|   \_/  \__, |\__\__,_|_| |_|\__,_|  |
 |                                       __/ |                       |
 |                                      |___/                        |
 *-------------------------------------------------------------------*/


#include "generator.h"

/**
 *	@brief	Generates the whole tree
 *
 *	@param	root	Root of the tree
 * 
 *	@return	SUCCESS 	If generating successful
 *	@return	INTERNAL_ERROR 	IF parameter root = NULL
 */
int generateTree(ASTRoot *root){
	if( root == NULL){
		fprintf(stderr, "ERROR!!! ROOT = NULL\n");
		return INTERNAL_ERROR;
	}

	printf("# Generated by KompIFJlator made by team 124 (Teamleader Ondřej Sloup xsloup02)\n");
	printf(".IFJcode20\n");
	printf("JUMP main\n");
	printf("#--------------- user funtions ---------------#\n");

	generateUserFunctions(root->userFunctions);
	generateMain(root->mainFunction);

	return SUCCESS;
}

/**
 *	@brief	Generates main function of given program
 *
 * 	@param	function 	Pointer to the function
 *
 *	@return	SUCCESS			If generating was successful
 *	@return	INTERNAL_ERROR	If param function is NULL and main does not exist
 */
int generateMain(ASTNodeFunction *function){
	if(function == NULL){
		fprintf(stderr, "missing main\n");
		return INTERNAL_ERROR;
	}

	printf("\n#------------------- main --------------------#\n");
	printf("\tLABEL main\n");
	printf("CREATEFRAME\n");
	printf("PUSHFRAME\n\n");

	generateFunctionBody(function);

	printf("\nPOPFRAME\n");
	printf("CREATEFRAME\n");
	//generateDebug();

	return SUCCESS;
}

/**
 *	@brief	Generates all user finctions by walking through linked list of functions
 *
 * 	@param	function 	Pointer to the first function
 */
void generateUserFunctions(ASTNodeFunction *function){
	while(function != NULL){
		generateFunction(function);
		function = function->next;
	}
}

/**
 *	@brief	Generates given function. (Only frame and calls generateFunctionBody)
 *
 * 	@param	function 	Pointer to the function definition. Guaranteed to NOT be NULL.
 */
void generateFunction(ASTNodeFunction *function){
	printf("WRITE string@New\\032function\\010\n\n");
	if(strCmpConstStr(&function->function->id, "main")){
		printf("LABEL %s\n", strGetStr(&function->function->id));
	}

	printf("PUSHFRAME\n\n");

	generateFunctionBody(function);

	printf("\nPOPFRAME\n");
	printf("RETURN\n");		// není náhodou RETURN už uložený v kodu ??
}

// Generates function body. Param function guaranteed to NOT be NULL.
void generateFunctionBody(ASTNodeFunction *function){
	printf("WRITE string@Hello\\032main!\\010\n");
	// definice všech promennych
	printf("#DEFVAR all of them.\n");
	


	// code 
}

// generates debug instruction to ifjcode output
void generateDebug(){
	printf("WRITE string@-------\\010\n");
	printf("BREAK\n");
	printf("WRITE string@-------\\010\n");
}
