/*File name: generator.c---------------------------------------------*
 |Project:    Implementace překladače imperativního jazyka IFJ20     |
 |Team:       124, varianta II                                       |
 |Authors:    Viktor Rucký (xrucky01)                                |
 |                                                                   |
 |  _      _     _   __                   __  _        _             |
 | | |    (_)   | | /_/                  /_/ | |      | |            |
 | | |     _  __| | ___   _   _  __   ___   _| |_ __ _| |__  _   _   |
 | | |    | |/ _` |/ _ \ | | | | \ \ / / | | | __/ _` | '_ \| | | |  |
 | | |____| | (_| |  __/ | |_| |  \ V /| |_| | || (_| | | | | |_| |  |
 | |______|_|\__,_|\___|  \__,_|   \_/  \__, |\__\__,_|_| |_|\__,_|  |
 |                                       __/ |                       |
 |                                      |___/                        |
 *-------------------------------------------------------------------*/


#include "generator.h"
#include <inttypes.h>
#define STRING_BUFFER_LENGTH 4096

/**
 *	@brief	Generates the whole tree
 *
 *	@param	root	Root of the tree
 * 
 *	@return	SUCCESS 	If generating successful
 *	@return	INTERNAL_ERROR 	IF parameter root = NULL
 */
int generateTree(ASTRoot *root){
	if( root == NULL){
		fprintf(stderr, "ERROR!!! ROOT = NULL\n");
		return INTERNAL_ERROR;
	}

	printf("# Generated by KompIFJlator made by team 124 (Teamleader Ondřej Sloup xsloup02)\n");
	printf(".IFJcode20\n");
	printf("JUMP main\n");
	printf("#--------------- user funtions ---------------#\n");

	generateUserFunctions(root->userFunctions);
	generateMain(root->mainFunction);

	return SUCCESS;
}

/**
 *	@brief	Generates main function of given program
 *
 * 	@param	function 	Pointer to the function
 *
 *	@return	SUCCESS			If generating was successful
 *	@return	INTERNAL_ERROR	If param function is NULL and main does not exist
 */
int generateMain(ASTNodeFunction *function){
	if(function == NULL){
		fprintf(stderr, "missing main\n");
		return INTERNAL_ERROR;
	}

	printf("\n#------------------- main --------------------#\n");
	printf("\tLABEL main\n");
	printf("CREATEFRAME\n");
	printf("PUSHFRAME\n\n");

	generateFunctionBody(function);

	printf("\nPOPFRAME\n");
	printf("CREATEFRAME\n");
	//generateDebug();

	return SUCCESS;
}

/**
 *	@brief	Generates all user finctions by walking through linked list of functions
 *
 * 	@param	function 	Pointer to the first function
 */
void generateUserFunctions(ASTNodeFunction *function){
	while(function != NULL){
		generateFunction(function);
		function = function->next;
	}
}

/**
 *	@brief	Generates given function. (Only frame and calls generateFunctionBody)
 *
 * 	@param	function 	Pointer to the function definition. Guaranteed to NOT be NULL.
 */
void generateFunction(ASTNodeFunction *function){
	printf("WRITE string@New\\032function\\010\n\n");
	if(strCmpConstStr(&function->function->id, "main")){
		printf("LABEL %s\n", strGetStr(&function->function->id));
	}

	printf("PUSHFRAME\n\n");

	generateFunctionBody(function);

	printf("\nPOPFRAME\n");
	printf("RETURN\n");		// není náhodou RETURN už uložený v kodu ??
}

// Generates function body. Param function guaranteed to NOT be NULL.
void generateFunctionBody(ASTNodeFunction *function){
	printf("WRITE string@Hello\\032main!\\010\n");
	// definice všech promennych
	printf("#DEFVAR all of them.\n");
	


	// code 
}

// generates debug instruction to ifjcode output
void generateDebug(){
	printf("WRITE string@-------\\010\n");
	printf("BREAK\n");
	printf("WRITE string@-------\\010\n");
}


char* generateVariableName(const SymbolVariable* var, char* out){
	int len = var->type != TypeBlackHole ? sprintf(out,"LF@uid_%d",var->uid) : sprintf(out,"nil@nil");
	if (len < 0)
		exit(INTERNAL_ERROR);
	return out + len;
}

char* generateIntLiteral(int64_t lit, char* out){
	int len = sprintf(out,"int@%"PRId64,lit);
	if (len < 0)
		exit(INTERNAL_ERROR);
	return out + len;
}

char* generateFloatLiteral(double lit, char* out){
	int len = sprintf(out, "float@%a",lit);
	if (len < 0)
		exit(INTERNAL_ERROR);
	return out + len;
}

char* generateStringLiteral(const char* lit,char* out){
	int len = sprintf(out, "string@");
	if (len < 0)
		exit(INTERNAL_ERROR);
	out += len;
	for(const char* i = lit; *i !='\0'; i++){
		if (*i <= 32 || *i == 35 || *i == 92){
			sprintf(out,"\\%3d",*i);
			out += 4;
		} else {
			*out = *i;
			out++;
		}
	}
	*out = '\0';
	return out;
}

char* generateTermRepresentation(const Term* term,char* out){
	switch(term->type){
		case TermFloatLiteral:
			return generateFloatLiteral(term->value.d,out);
		case TermIntegerLiteral:
			return generateIntLiteral(term->value.i,out);
		case TermStringLiteral:
			return generateStringLiteral(strGetStr(&term->value.s),out);
		case TermVariable:
			return generateVariableName(term->value.v,out);
		default:
			exit(INTERNAL_ERROR); //Shouldn't get to this line.
	}
}

void generateBuiltInPrint(ASTNodeFunctionCall* printCall){
	for (int i = 0; i <printCall->parameters.count;i++){
		char argBuffer[STRING_BUFFER_LENGTH];
		generateTermRepresentation(printCall->parameters.arr[i],argBuffer);
		printf("WRITE %s\n",argBuffer);
	}
}