name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make -C ./src/
    - name: make check
      run: make -C ./src/ check
    - name: make distcheck
      run: make -C ./src/ distcheck
